In [148]:
t = """[[5.20800000e+002             0 8.80000000e+000 1.04000000e+001
  1.00000000e-001 1.02200000e+002 4.10000000e+000 7.00000000e-001
  3.48000000e+001 1.90000000e+000]
 [4.00000000e-001             0 3.99000000e+001 8.10000000e+000
  7.00000000e+000 2.37000000e+001 7.20000000e+000 2.20000000e+001
  1.08600000e+002 1.48000000e+001]
 [            0 1.75000000e+001 7.91500000e+002 4.74000000e+001
  1.80000000e+000 4.32000000e+001 2.02000000e+001 2.72000000e+001
  1.26500000e+002 5.20000000e+000]
 [            0 1.15000000e+001 4.66000000e+001 8.50200000e+002
  3.60000000e+000 1.51100000e+002 2.70000000e+000 2.26000000e+001
  1.56600000e+002             0]
 [4.38000000e+001 7.00000000e-001 4.25000000e+001 5.10000000e+000
  8.13500000e+002 6.85000000e+001 6.20000000e+001 4.95000000e+001
  1.01100000e+002             0]
 [6.86000000e+001 1.20000000e+001 9.00000000e+000 1.81000000e+001
  8.68995162e-313 1.70600000e+002 3.50000000e+000 7.00000000e-001
              0 8.68995584e-313]
 [1.36200000e+002 5.10000000e+000 4.53000000e+001 1.17000000e+001
  4.29000000e+001 1.31400000e+002 8.48800000e+002 3.80000000e+000
              0 9.70000000e+000]
 [3.46000000e+001 1.00000000e+000 2.09000000e+001 2.48000000e+001
  2.80000000e+000 7.60000000e+001 1.00000000e-001             0
  5.77000000e+001 7.83000000e+001]
 [1.82000000e+001 6.30000000e+000 4.40000000e+000 9.00000000e+000
  1.00000000e-001 5.93000000e+001 1.90000000e+000             0
  4.05000000e+001 1.00000000e-001]
 [6.99000000e+001 2.20000000e+000 2.31000000e+001 2.52000000e+001
  1.10200000e+002 6.60000000e+001             0 6.04000000e+001
  1.31000000e+002 5.55900000e+002]]
"""
  
digits = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
formatted = ""
for (i, char) in enumerate(t):
  if char in digits:
    if t[i+1] == ' ' or t[i+1] == '\n':
      formatted += char
      formatted += ','
    else:
      formatted += char
  elif char == ']':
    if i < len(t) - 3 and t[i+3] == '[':
      formatted += ']'
      formatted += '#'
    else:
      formatted += ']'
  else:
    formatted += char

#print(formatted.split('#'))
restored = []
for l in formatted.split('#'):
  floated = []
  temp = l.replace('[', '').replace(']', '')
  for num in temp.split(','):
    floated.append(float(num))
  restored.append(floated)

In [149]:
import numpy as np
x = np.fromstring(np.array(restored), count=100).reshape(10, 10)

row_labels = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']
column_labels = ['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

C:\Users\siema\AppData\Local\Temp\ipykernel_1744\4280111391.py:2: DeprecationWarning: The binary mode of fromstring is deprecated, as it behaves surprisingly on unicode inputs. Use frombuffer instead
  x = np.fromstring(np.array(restored), count=100).reshape(10, 10)

In [150]:
import pandas
pandas.set_option('display.float_format', lambda x: '%.2f' % x)
df = pandas.DataFrame(x, columns=column_labels, index=row_labels)

df

       0     1      2      3      4      5      6     7      8      9
0 520.80  0.00   8.80  10.40   0.10 102.20   4.10  0.70  34.80   1.90
1   0.40  0.00  39.90   8.10   7.00  23.70   7.20 22.00 108.60  14.80
2   0.00 17.50 791.50  47.40   1.80  43.20  20.20 27.20 126.50   5.20
3   0.00 11.50  46.60 850.20   3.60 151.10   2.70 22.60 156.60   0.00
4  43.80  0.70  42.50   5.10 813.50  68.50  62.00 49.50 101.10   0.00
5  68.60 12.00   9.00  18.10   0.00 170.60   3.50  0.70   0.00   0.00
6 136.20  5.10  45.30  11.70  42.90 131.40 848.80  3.80   0.00   9.70
7  34.60  1.00  20.90  24.80   2.80  76.00   0.10  0.00  57.70  78.30
8  18.20  6.30   4.40   9.00   0.10  59.30   1.90  0.00  40.50   0.10
9  69.90  2.20  23.10  25.20 110.20  66.00   0.00 60.40 131.00 555.90